---
title: "karolina Testat"
output: html_document
date: '2022-05-12'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r Netzwerk einlesen, fig.height=6, fig.width=10, message=FALSE, warning=TRUE, paged.print=FALSE}

library(igraph)

edge <- read.csv("https://raw.githubusercontent.com/Karo2202/Testat-VfB/main/testat%20karo%20vfb%20-%20Edgelist.csv", header = T, as.is = T, sep=",")
edge


nodes <- read.csv("https://raw.githubusercontent.com/Karo2202/Testat-VfB/main/testat%20karo%20vfb%20-%20Nodelist.csv", header=T, as.is=T, sep = ",")
nodes

edgematrix <-as.matrix(edge)
edgematrix


#igraph Objekt erstellen
VfB <- graph_from_data_frame(d=edgematrix, directed=T)
VfB


```
```{r Netzwerk visualisieren, fig.height=6, fig.width=10}

plot(VfB, 
		 asp=0,
     layout=layout_nicely,
     main="VfB Transfer",
     sub="kb138",
		 vertex.size= degree(VfB),
     vertex.color="gold",
     vertex.frame.color=NA,
     edge.color="red",
     edge.curved=.2,
     edge.arrow.size=.2)
```